# Podfile for SyncFlowMac
# WebRTC is now added via Swift Package Manager (stasel/WebRTC)
# This Podfile is kept empty for reference.

source 'https://cdn.cocoapods.org/'

platform :macos, '14.0'

target 'SyncFlowMac' do
  use_frameworks!
end
